export const PARAGRAPH = [
  // `<h1>I'm send­ing you the film slides of the present­a­tion boards. Milan, June 5 1972</h1>`,
  // `<blockquote>`,
  // `<p>Why is Tailwind removing the default styles on my <code>h1</code> elements? How do I disable this? What do you mean I lose all the other base styles too?</p>`,
  // `</blockquote>`,
  `<p><b>Lorehaven,</b> a jewel nestled amidst the sapphire expanse of the Southern Seas, was a land steeped in myth and legend. Lush rainforests, teeming with exotic flora and fauna, cloaked volcanic peaks that scraped the underbelly of the clouds. Crystal-clear rivers snaked through valleys carpeted with emerald ferns, their waters cascading into hidden lagoons fringed with pristine white sand. Towering waterfalls, their thunder echoing through the verdant canopy, plummeted into shimmering pools, their beauty a constant source of awe for the island's inhabitants.</p>`,
  // `<figure>`,
  // `<img src="/images/armin-h3RoWx7Vd20-unsplash.jpg" alt="Sample Image 1" />`,
  // `<figcaption>`,
  // `<em>This is caption</em>`,
  // `</figcaption>`,
  // `</figure>`,
  `<p><em>Life on <b>Lorehaven</b></em> wasn't always idyllic. The island was prone to unpredictable storms, unleashed with the fury of a scorned god. Torrents of rain lashed the landscape, rivers overflowed their banks, and monstrous waves, taller than the tallest trees, threatened to devour the coastline. These tempests were said to be the wrath of the ancient sea serpent, Leviathan, slumbering in the ocean's depths.</p>`,
  `<p>The <mark>Aethelfolk,</mark> however, <mark>had developed a sophisticated system of storm prediction</mark> based on <mark>celestial movements and animal behavior,</mark> allowing them to weather these challenges with resilience and respect for the power of nature.</p>`,
  // `<h1>Rocketship goes by — Goodnight Electric.</h1>`,
  // `<p><em>However,</em> a shadow loomed over the horizon. Whispers of a forgotten magic, a dark force stirring in the heart of the volcano, crept through the villages. Fear flickered in the eyes of elders, a stark contrast to the usual twinkle of amusement. Young warriors honed their skills with uncharacteristic seriousness, the rhythmic clang of their practice blades echoing a growing unease. Lorehaven, the enchanting isle, was about to face a test that would challenge the very fabric of its existence.</p>`,
  // `<h1>Rocketship goes by — Goodnight Electric.</h1>`,
  `<p>Witchfinder General (titled onscreen as Matthew Hopkins: Witchfinder General) is a 1968 British period horror film directed by <b>Michael Reeves</b> and starring Vincent Price, Ian Ogilvy, Hilary Dwyer, Robert Russell and Rupert Davies. The screenplay, by Reeves and Tom Baker, [a] was based on Ronald Bassett's 1966 novel Witchfinder General. The film is a heavily fictionalised account of the murderous witch-hunting exploits of <em>Matthew Hopkins (Price),</em> a lawyer who falsely claimed to have been appointed as a Witch Finder General by Parliament during the English Civil and his assistant John Stearne (Russell) after they prey on his fiancée Sara (Dwyer) and execute her priestly uncle John Lowes (Davies).</p>`,
  `<p>Made on a low budget of under £100,000, the film was produced by Tigon British Film Productions. In the United States, where it was distributed by American International Pictures (AIP), <mark>Witchfinder General was retitled</mark> The Conqueror Worm (titled onscreen as Matthew Hopkins: Conqueror Worm) by AIP to link it with their earlier series of Edgar Allan Poe adaptations directed by Roger Corman and starring.</p>`,
  // `<figure>`,
  // `<img src="/images/stacey-knipe-ob8H3alg4Uw-unsplash.jpg" />`,
  // `<figcaption>`,
  // `<em>This is caption should be as long as possible brother.</em>`,
  // `</figcaption>`,
  // `</figure>`,
];

export const LIPSUM = [
  `<h1>What is Lorem Ipsum?</h1>`,
  `<p><b>Lorem Ipsum</b> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>`,
  `<h2>Why do we use it?</h2>`,
  `<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>`,
  `<h2>Where does it come from?</h2>`,
  `<p>Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>`,
  `<p>The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.</p>`,
  `<h2>Where can I get some?</h2>`,
  `<p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</p>`,
];
